=== Vishtar/sec.cyou/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "minLength": 1,
                "description": "The name of the exchange."
            },
            "website": {
                "type": "string",
                "description": "The website URL of the exchange.",
                "minLength": 1,
                "format": "uri"
            },
            "description": {
                "type": "string",
                "minLength": 1,
                "description": "A description of the exchange."
            },
            "tags": {
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": [
                        "perpetual exchange",
                        "forex",
                        "swaps",
                        "atomic swaps",
                        "cross-chain swaps",
                        "open source",
                        "binary options",
                        "aggregator",
                        "ecosystem",
                        "oracle",
                        "derivatives",
                        "bridge",
                        "automated market maker",
                        "order book",
                        "address screening",
                        "osmosis ecosystem",
                        "testnet-only",
                        "Synthetic Assets",
                        "synthetix ecosystem",
                        "leveraged yield farming",
                        "yield farming",
                        "uma ecosystem"
                    ]
                },
                "description": "Tags categorizing the exchange."
            },
            "coins": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "description": "List of supported coins."
            },
            "chains": {
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": [
                        "Arbitrum One",
                        "Polygon",
                        "Bitcoin",
                        "Bitcoin Cash",
                        "Monero",
                        "Ethereum",
                        "Optimism",
                        "Binance Smart Chain",
                        "Avalanche",
                        "Fantom",
                        "Solana",
                        "Cronos",
                        "Base",
                        "zkSync Era",
                        "Celo",
                        "Aurora",
                        "Harmony",
                        "xDai",
                        "Moonbeam",
                        "Kava",
                        "Polygon zkEVM",
                        "Aptos",
                        "Osmosis",
                        "Gnosis",
                        "Arbitrum Nova",
                        "Cardano",
                        "Stella"
                    ]
                },
                "description": "List of supported blockchain chains."
            },
            "docs": {
                "type": "string",
                "description": "URL to the documentation.",
                "format": "uri"
            },
            "twitter": {
                "type": "string",
                "description": "URL to the Twitter profile.",
                "format": "uri"
            },
            "discord": {
                "type": "string",
                "description": "URL to the Discord server.",
                "format": "uri"
            },
            "github": {
                "type": "string",
                "description": "URL to the GitHub repository.",
                "format": "uri"
            },
            "telegram": {
                "type": "string",
                "description": "Telegram link.",
                "format": "uri"
            },
            "medium": {
                "type": "string",
                "description": "Medium URL.",
                "format": "uri"
            },
            "mirror": {
                "type": "string",
                "description": "Mirror.xyz of the platform.",
                "format": "uri"
            },
            "roadmap": {
                "type": "string",
                "description": "Mirror.xyz of the platform.",
                "format": "uri"
            },
            "roadmap": {
                "type": "string",
                "description": "Mirror.xyz of the platform.",
                "format": "uri"
            },
            "sourceUrl": {
                "type": "string",
                "description": "URL to the source code.",
                "format": "uri"
            },
            "maxLeverage": {
                "type": "number",
                "description": "Maximum leverage provided by the exchange."
            },
            "leverageInfo": {
                "type": "string",
                "description": "Maximum leverage provided by the exchange."
            },
            "opensource": {
                "type": "boolean",
                "description": "Indicates whether the exchange is open source."
            }
        },
        "required": ["name", "website", "description", "tags", "chains"],
        "additionalProperties": false
    }
}

=== Vishtar/sec.cyou/src/list.json
[
    {
        "name": "Vela Exchange",
        "website": "https://vela.exchange",
        "description": "Trade with up to 250x leverage across crypto, forex, metals and more",
        "tags": [
            "perpetual exchange",
            "forex"
        ],
        "chains": [
            "Arbitrum One"
        ],
        "docs": "https://docs.vela.exchange/vela-knowledge-base/exchange/platform-overview",
        "twitter": "https://twitter.com/vela_exchange",
        "telegram": "https://t.me/vela_exchange",
        "discord": "https://discord.com/invite/velaexchange",
        "maxLeverage": 250,
        "leverageInfo": "https://www.vela.exchange/whitepaper.pdf"
    },
    {
        "name": "gTrade",
        "website": "https://gains.trade/",
        "description": "Leverage trade on crypto, forex, and commodities",
        "tags": [
            "perpetual exchange",
            "forex"
        ],
        "chains": [
            "Arbitrum One",
            "Polygon"
        ],
        "docs": "https://gains-network.gitbook.io/",
        "twitter": "https://twitter.com/GainsNetwork_io",
        "telegram": "https://t.me/GainsNetwork",
        "discord": "https://discord.com/invite/gains-network",
        "github": "https://github.com/GainsNetwork-org",
        "maxLeverage": 150,
        "leverageInfo": "https://gains-network.gitbook.io/docs-home/gtrade-leveraged-trading/asset-classes"
    },
    {
        "name": "GMX",
        "website": "https://gmx.io/",
        "description": "Trade BTC, ETH, AVAX and other with up to 50x leverage from your wallet",
        "tags": [
            "perpetual exchange"
        ],
        "chains": [
            "Arbitrum One",
            "Avalanche"
        ],
        "docs": "https://docs.gmx.io/",
        "twitter": "https://twitter.com/GMX_IO",
        "telegram": "https://t.me/GMX_IO",
        "discord": "https://discord.com/invite/ymN38YefH9",
        "github": "https://github.com/gmx-io",
        "maxLeverage": 50,
        "leverageInfo": "https://docs.gmx.io/docs/trading/v2"
    },
    {
        "name": "UnstoppableSwap",
        "website": "https://unstoppableswap.net/",
        "description": "Exchange Bitcoin for Monero using Atomic Swaps. No registration, no KYC, no middleman and anonymous over Tor network.",
        "tags": [
            "swaps",
            "atomic swaps",
            "cross-chain swaps",
            "open source"
        ],
        "coins": [
            "BTC",
            "XMR"
        ],
        "chains": [
            "Bitcoin",
            "Monero"
        ],
        "docs": "https://github.com/UnstoppableSwap/unstoppableswap-gui/tree/main/docs",
        "twitter": "https://twitter.com/UnstoppableSwap",
        "github": "https://github.com/UnstoppableSwap/unstoppableswap-gui"
    },
    {
        "name": "dYdX",
        "website": "https://dydx.exchange/",
        "description": "Trade Perpetual Contracts with low fees, deep liquidity, and up to 20Ã— more Buying Power",
        "tags": [
            "perpetual exchange"
        ],
        "chains": [
            "Ethereum"
        ],
        "docs": "https://v4-teacher.vercel.app/",
        "twitter": "https://twitter.com/dydx",
        "discord": "https://discord.com/invite/Tuze6tY",
        "github": "https://github.com/dydxprotocol/",
        "maxLeverage": 20
    },
    {
        "name": "Perpetual Protocol",
        "website": "https://app.perp.com/",
        "description": "Designed to facilitate the trading of derivatives known as perpetual contracts.",
        "tags": [
            "perpetual exchange"
        ],
        "chains": [
            "Optimism"
        ],
        "twitter": "https://twitter.com/perpprotocol",
        "telegram": "https://t.me/perpetualprotocol",
        "discord": "https://discord.com/invite/mYKKRTn",
        "github": "https://github.com/perpetual-protocol",
        "maxLeverage": 10
    },
    {
        "name": "Metavault Trade",
        "website": "https://metavault.trade/",
        "description": "Decentralized spot & perpetual exchange.",
        "tags": [
            "perpetual exchange",
            "binary options"
        ],
        "chains": [
            "Polygon"
        ],
        "twitter": "https://www.twitter.com/metavaulttrade/",
        "telegram": "https://t.me/MetavaultTrade/",
        "discord": "https://discord.com/invite/metavault",
        "github": "https://github.com/metavaultorg/",
        "maxLeverage": 50,
        "leverageInfo": "https://docs.metavault.trade/trading-features/perpetual-and-spot-trading/what-is-spot-and-perp-trading#leveraged-instrument"
    },
    {
        "name": "MUX",
        "website": "https://mux.network/",
        "description": "MUX dynamically routes positions to suited underlying trading protocols.",
        "tags": [
            "perpetual exchange",
            "aggregator"
        ],
        "chains": [
            "Arbitrum One",
            "Binance Smart Chain",
            "Avalanche",
            "Optimism",
            "Fantom"
        ],
        "twitter": "https://twitter.com/muxprotocol",
        "telegram": "https://t.me/muxprotocol",
        "discord": "https://discord.com/invite/bd88NrzN3N",
        "github": "https://github.com/mux-world/mux-protocol",
        "maxLeverage": 100,
        "leverageInfo": "https://docs.mux.network/protocol/overview/leveraged-trading-protocol"
    },
    {
        "name": "Kwenta",
        "website": "https://kwenta.eth.limo/",
        "description": "Decentralized derivatives trading platform. Gain exposure to a variety of on-chain and real-world assets, and advanced functionality through the Kwenta Smart Margin Wallet.",
        "tags": [
            "perpetual exchange",
            "Synthetic Assets",
            "synthetix ecosystem"
        ],
        "chains": [
            "Optimism"
        ],
        "twitter": "https://twitter.com/kwenta_io",
        "discord": "http://discord.gg/kwentaio",
        "github": "https://github.com/Kwenta",
        "maxLeverage": 50,
        "leverageInfo": "https://docs.kwenta.io/using-kwenta/perpetual-futures/leverage"
    },
    {
        "name": "Apex",
        "website": "https://www.apex.exchange/",
        "description": "ApeX Pro is a non-custodial trading platform that delivers limitless cross-margined perpetual contracts to its metacommunity under a new social trading framework",
        "tags": [
            "perpetual exchange"
        ],
        "chains": [
            "Ethereum",
            "Binance Smart Chain",
            "Polygon",
            "Arbitrum One",
            "Avalanche",
            "Optimism"
        ],
        "docs": "https://apex-pro.gitbook.io/apex-pro/",
        "twitter": "https://twitter.com/OfficialApeXdex",
        "telegram": "https://t.me/ApeXdex",
        "discord": "https://discord.com/invite/366Puqavwx",
        "github": "https://github.com/ApeX-Protocol"
    },
    {
        "name": "ApolloX",
        "website": "https://www.apollox.finance/",
        "description": "Trade crypto perpetuals with up to 500x leverage, low fees, and the lowest slippage on the market",
        "tags": [
            "perpetual exchange"
        ],
        "chains": [
            "Binance Smart Chain"
        ],
        "twitter": "https://twitter.com/ApolloX_Finance",
        "telegram": "https://t.me/apolloxchange",
        "discord": "https://discord.com/invite/q5eH3zktcm",
        "github": "https://github.com/apollox-finance",
        "maxLeverage": 500,
        "leverageInfo": "https://apollox-finance.gitbook.io/apollox-finance/welcome/trading-on-v1/how-to-start-trading-on-apollox/margin-mode-and-leverage"
    },
    {
        "name": "Level Finance",
        "website": "https://level.finance/",
        "description": "Omnichain Liquidity Marketplace with Functional Risk Management",
        "tags": [
            "perpetual exchange"
        ],
        "chains": [
            "Arbitrum One",
            "Binance Smart Chain"
        ],
        "twitter": "https://twitter.com/level__finance",
        "telegram": "https://t.me/LevelFinance",
        "discord": "https://discord.com/invite/levelfinance",
        "github": "https://github.com/level-fi",
        "maxLeverage": 50
    },
    {
        "name": "Mango Markets",
        "website": "https://mango.markets/",
        "description": "Solana and Serum blockchain-powered platform, all-in-one trading platform for spot markets, derivatives assets, lending and borrowing",
        "tags": [
            "perpetual exchange"
        ],
        "chains": [
            "Solana"
        ],
        "twitter": "https://twitter.com/mangomarkets",
        "discord": "https://discord.com/invite/8vs8uJJrcp",
        "github": "https://github.com/blockworks-foundation",
        "maxLeverage": 20,
        "leverageInfo": "https://docs.mango.markets/mango-v3-deprecated/perp-faq#how-much-leverage-can-i-take"
    },
    {
        "name": "Synthetix Ecosystem",
        "website": "https://synthetix.io/",
        "description": "Provides liquidity for permissionless derivatives like perpetual futures, options, parimutuel markets, and more across EVM chains.",
        "tags": [
            "ecosystem",
            "synthetix ecosystem"
        ],
        "chains": [
            "Ethereum"
        ],
        "twitter": "https://twitter.com/synthetix_io",
        "discord": "https://discord.com/invite/AEdUHzt",
        "github": "https://github.com/synthetixio",
        "leverageInfo": "https://docs.synthetix.io/v/v3/for-developers/smart-contracts#setcollateralleverage"
    },
    {
        "name": "Fulcrom",
        "website": "https://fulcrom.finance/",
        "description": "Decentralized perpetual exchange on Cronos for leverage trading with minimal fees and price impact, and staking",
        "tags": [
            "perpetual exchange"
        ],
        "chains": [
            "Cronos"
        ],
